[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NODE_VERSION = "18"
  PYENV_VERSION = "3.10.13"
  # Skip submodule processing since this repo does not use submodules
  GIT_SUBMODULE_STRATEGY = "none"
  # Build optimizations
  CI = "true"
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

# Security headers with Stripe support
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com https://checkout.stripe.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://images.pexels.com https://*.supabase.co https://*.netlify.app; connect-src 'self' https://*.supabase.co https://api.openai.com https://api.elevenlabs.io https://api.spoonacular.com https://*.netlify.app https://api.stripe.com wss://*.supabase.co; object-src 'none'; frame-src 'self' https://js.stripe.com https://hooks.stripe.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS and JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Custom domain configuration
[[redirects]]
  from = "https://biowell.ai/*"
  to = "/:splat"
  status = 200
  force = true

# API redirects (if you have backend API)
[[redirects]]
  from = "/api/*"
  to = "https://api.biowell.ai/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment-specific deployments
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"
  VITE_ENV = "production"

[context.deploy-preview]
  command = "npm run build"
  
[context.deploy-preview.environment]
  NODE_ENV = "staging"
  VITE_ENV = "staging"

[context.branch-deploy]
  command = "npm run build"

# Dev settings for netlify dev
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  autoLaunch = false